-- Create the Dishes table
CREATE TABLE Dishes (
    dish_id VARCHAR(4) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Meal_Category ENUM('Veg', 'Non-Veg', 'Jain') NOT NULL
);

INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D001', 'Aakha Masoor Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D002', 'Achar Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D003', 'Achari Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D004', 'Afghani Chicken', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D005', 'Akha Masoor', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D006', 'Aloo Beans Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D007', 'Aloo Capsicum Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D008', 'Aloo Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D009', 'Aloo Gobi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D010', 'Aloo Gobi Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D011', 'Aloo Jeera', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D012', 'Aloo Matar', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D013', 'Aloo Methi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D014', 'Aloo Mutter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D015', 'Aloo Mutter Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D016', 'Aloo Mutter Rassa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D017', 'Aloo Mutter Red Gravy', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D018', 'Aloo Palak', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D019', 'Aloo Palak Lassoni Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D020', 'Aloo Papadi Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D021', 'Aloo Papdi Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D022', 'Aloo Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D023', 'Aloo Rassa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D024', 'Aloo Sabji Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D025', 'Aloo Sabji Khatri Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D026', 'Aloo Shimla Mirch Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D027', 'Aloo Sukkha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D028', 'Alu Mutter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D029', 'Angara Murg Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D030', 'Baby Potato Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D031', 'Baghara Black Chana', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D032', 'Baigan Bharta', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D033', 'Baigan Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D034', 'Baingan Bharta', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D035', 'Baingan Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D036', 'Bambaya Murmura Bhel', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D037', 'Banana', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D038', 'Bangali Bhaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D039', 'Bangli Bhaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D040', 'Batatyache Kaap', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D041', 'Beans Aloo Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D042', 'Beans Cabbage Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D043', 'Beans Porial', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D044', 'Beans Poriyal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D045', 'Beet Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D046', 'Beetroot Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D047', 'Beetroot Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D048', 'Beetroot, Carrot', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D049', 'Bengali Cholar Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D050', 'Bengali Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D051', 'Bengan Bartha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D052', 'Besan Chilla', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D053', 'Bhaji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D054', 'Bhatura', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D055', 'Bhature', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D056', 'Bhindi Dahiwali', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D057', 'Bhindi Do Pyaza', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D058', 'Bhindi Kukure', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D059', 'Bhindi Kurkura', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D060', 'Bhindi Onion Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D061', 'Black Chana', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D062', 'Black Chana Rassa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D063', 'Black Channa Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D064', 'Black Coffee', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D065', 'Black Tea', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D066', 'Boiled Channa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D067', 'Boiled Chicken', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D068', 'Boiled Egg Bhurji', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D069', 'Boiled Macroni Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D070', 'Boiled Peanuts', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D071', 'Bombay Bhel', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D072', 'Bombay Bread Pakoda', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D073', 'Bombay Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D074', 'Bombay Toast Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D075', 'Bombeay Bhel', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D076', 'Boondi Raita', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D077', 'Bread', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D078', 'Bread (Brown/White Option)', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D079', 'Bread Pakoda', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D080', 'Brown Onion Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D081', 'Brown Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D082', 'Butter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D083', 'Butter Chicken', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D084', 'Butter Chicken with Bone', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D085', 'Butter Corn', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D086', 'Butter Corn Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D087', 'Butter Kulcha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D088', 'Butter Milk', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D089', 'Butter Paneer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D090', 'Buttermilk', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D091', 'Cabbage Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D092', 'Cabbage Chana', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D093', 'Cabbage Chana Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D094', 'Cabbage Channa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D095', 'Cabbage Channa Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D096', 'Cabbage Mutter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D097', 'Cabbage Poriyal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D098', 'Capsicum Aloo Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D099', 'Capsicum Corn Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D100', 'Caret Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D101', 'Carrot Beetroot Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D102', 'Carrot Kheer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D103', 'Carrot Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D104', 'Carrot Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D105', 'Carrot/Cucumber Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D106', 'Carrots Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D107', 'Chana Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D108', 'Chana Dal Tadaka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D109', 'Chana Dal Tadka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D110', 'Chana Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D111', 'Channa Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D112', 'Chapati', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D113', 'Charminar Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D114', 'Chawali Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D115', 'Chawle', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D116', 'Chawli Masaal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D117', 'Chawli Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D118', 'Chenna Kheer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D119', 'Chicken Biryani', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D120', 'Chicken Chettinad', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D121', 'Chicken Chilli', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D122', 'Chicken Do Pyaza', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D123', 'Chicken Fry Rice', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D124', 'Chicken Gavran', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D125', 'Chicken Hyderabadi Biryani', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D126', 'Chicken Kalimiri', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D127', 'Chicken Kolhapuri', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D128', 'Chicken Madras Curry', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D129', 'Chicken Masala', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D130', 'Chicken Pahadi Masala', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D131', 'Chicken Rassa', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D132', 'Chicken Tambda Rassa Pandhra Rassa', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D133', 'Chicken Tikka Franky', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D134', 'Chicken Tikka Masala', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D135', 'Chicken Tikka Rolls', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D136', 'Chicken Tikka Wrap', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D137', 'Chicken Yakhni Pulao', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D138', 'Chilli Soya', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D139', 'Cholar Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D140', 'Chole', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D141', 'Chole Amritsari', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D142', 'Chole Amrutsari', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D143', 'Chole Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D144', 'Chole Pindi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D145', 'Chollar Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D146', 'Chop Cucumber, Onion, Beetroot, Carrot', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D147', 'Chop Tomato, Cucumber, Onion, Carrot', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D148', 'Chowli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D149', 'Chutney Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D150', 'Cobb Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D151', 'Coconet Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D152', 'Coconut Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D153', 'Coconut Gulab Jamun', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D154', 'Coffee', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D155', 'Coleslaw Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D156', 'Coriander Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D157', 'Coriander Rice Green', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D158', 'Corn & Anar Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D159', 'Corn Capsicum Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D160', 'Corn Carrot Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D161', 'Corn Flakes', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D162', 'Corn Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D163', 'Corn Mint Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D164', 'Corn On The Cob', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D165', 'Corn Palak', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D166', 'Corn Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D167', 'Corn Spinach Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D168', 'Cube Cut Carrot, Cucumber, Beetroot', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D169', 'Cube Cut Tomato, Cucumber, Carrot, Onion', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D170', 'Cucumber Carrot Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D171', 'Cucumber Honey Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D172', 'Cucumber Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D173', 'Cucumber, Carrot, Onion', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D174', 'Curd', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D175', 'Curd Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D176', 'Cut Fruit', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D177', 'Cut Fruit - Papaya', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D178', 'Cut Fruit - Watermelon', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D179', 'Cut Papaya', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D180', 'Cut Watermelon', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D181', 'Dabeli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D182', 'Dahi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D183', 'Dahi Kadhi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D184', 'Dahi Kadi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D185', 'Dahi Lauki Ki Sabji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D186', 'Dahi Vada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D187', 'Dahi Wada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D188', 'Dahiwali Bhindi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D189', 'Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D190', 'Dal Adhraki', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D191', 'Dal Adraki', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D192', 'Dal Bukhara', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D193', 'Dal Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D194', 'Dal Fry Lasuni', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D195', 'Dal Khichadi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D196', 'Dal Khichdi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D197', 'Dal Ki Kachori', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D198', 'Dal Kolhapuri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D199', 'Dal Lasooni', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D200', 'Dal Makhani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D201', 'Dal Palak', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D202', 'Dal Panchmeal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D203', 'Dal Panchrathan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D204', 'Dal Pilen', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D205', 'Dal Tadka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D206', 'Dal Tadkewali', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D207', 'Dal Trivani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D208', 'Dal Triveni', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D209', 'Dalia Upma', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D210', 'Dhabewali Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D211', 'Doodhi Chana Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D212', 'Doodhi Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D213', 'Doodhi Hara Pyaz', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D214', 'Doodhi Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D215', 'Doodhi Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D216', 'Doodi Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D217', 'Dosa Bhaji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D218', 'Dragon Potato', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D219', 'Dragon Potatoes', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D220', 'Dudhi Chana Dal Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D221', 'Dudhi Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D222', 'Dum Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D223', 'Dum Aloo Bengali', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D224', 'Dum Aloo Bengali Style', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D225', 'Dum Aloo Kashmiri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D226', 'Dum Aloo Punjabi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D227', 'Dum Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D228', 'Egg Bhurji', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D229', 'Egg Curry', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D230', 'Egg Rolls', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D231', 'Eggs Bhaji', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D232', 'Eggs Fry', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D233', 'Eggs To Order', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D234', 'Fine Chop Tomato, Cucumber, Onion', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D235', 'Fodani Cha Bhat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D236', 'Fruit Custard', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D237', 'Fruit Punch', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D238', 'Fry Idli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D239', 'Gatte Ki Sabji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D240', 'Gatte Ki Subji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D241', 'Gavar Poriyal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D242', 'Gawar Ki Sabji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D243', 'Ghee Bhat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D244', 'Ghee Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D245', 'Gobhi Mutter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D246', 'Gobi & Aloo Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D247', 'Gobi & Alu Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D248', 'Gobi Aloo Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D249', 'Gobi Aloo Stuffed Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D250', 'Gobi Capsicum Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D251', 'Gobi Matar Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D252', 'Gobi Mutter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D253', 'Gobi Mutter Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D254', 'Greek Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D255', 'Green Chavali Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D256', 'Green Chilli Thecha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D257', 'Green Chilly Thecha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D258', 'Green Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D259', 'Green Dal Moog', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D260', 'Green Moong', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D261', 'Green Moong Dal Tadaka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D262', 'Green Moong Sprout Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D263', 'Green Moong Ussal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D264', 'Green Moong Ussal Tadaka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D265', 'Green Peas Poha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D266', 'Green Rice (Coriander & Garlic)', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D267', 'Green Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D268', 'Gulab Jamun', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D269', 'Gwar Fali Ki Sabji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D270', 'Home Style Bhindi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D271', 'Hot & Cold Milk', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D272', 'Idli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D273', 'Idli Mysore', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D274', 'Imli Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D275', 'Jalebi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D276', 'Jam', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D277', 'Jeera Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D278', 'Jeera Dhaniya Dum Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D279', 'Jeera Dhaniya Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D280', 'Jeera Moong Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D281', 'Jeera Moong Dal Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D282', 'Jeera Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D283', 'Julian Cut Carrot, Cucumber', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D284', 'Julian Cut Carrot, Cucumber Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D285', 'Julian Cut Carrot, Cucumber, Raddish, Red Cabbage', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D286', 'Julian Cut Carrot, Cucumber, Radish, Red Cabbage', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D287', 'Julienne Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D288', 'Kachumber', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D289', 'Kadha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D290', 'Kala Chana Rassa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D291', 'Kala Channa Rassa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D292', 'Kalimiri Chicken', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D293', 'Kanda Pakoda', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D294', 'Kanjipuram Idli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D295', 'Karela Aloo Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D296', 'Karela Pyaz Ki Sabzi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D297', 'Karela Sabzi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D298', 'Karele Pyaz Ki Sabzi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D299', 'Kashmiri Chicken', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D300', 'Kashmiri Dum Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D301', 'Kashmiri Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D302', 'Katchi Dabeli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D303', 'Ketchup', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D304', 'Khadi Pakora', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D305', 'Khaman Dhokla', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D306', 'Khekada Bhajji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D307', 'Khichadi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D308', 'Khimchi Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D309', 'Kimchi Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D310', 'Kiwi Cooler', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D311', 'Koshibir Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D312', 'Koshimibir Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D313', 'Kulcha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D314', 'Kurkure Bhindi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D315', 'Laccha Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D316', 'Lachha Masala Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D317', 'Lachha Onion', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D318', 'Lachha Onion Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D319', 'Lachha Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D320', 'Lapsi Sheera', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D321', 'Lasooni Dal Tadka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D322', 'Lasooni Palak', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D323', 'Lauki Halwa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D324', 'Lauki Ki Sabji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D325', 'Lauki Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D326', 'Lemon', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D327', 'Lemon & Sev', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D328', 'Lemon Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D329', 'Lemon Wedges', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D330', 'Lemon/Sev', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D331', 'Louki Chana Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D332', 'Luchi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D333', 'Macaroni (Maggi Masala Indian Style)', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D334', 'Macaroni Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D335', 'Macroni (Maggi Masala Indian Style)', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D336', 'Macroni Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D337', 'Maggi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D338', 'Maharashtrian Kadhi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D339', 'Malabari Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D340', 'Malai Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D341', 'Malavani Eggs Curry', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D342', 'Malvani Chicken Curry', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D343', 'Malvani Eggs Curry', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D344', 'Malvani Paneer Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D345', 'Manchow Soup', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D346', 'Masala Aloo Poha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D347', 'Masala Bhaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D348', 'Masala Bhat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D349', 'Masala Chaas', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D350', 'Masala Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D351', 'Masala Lauki', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D352', 'Masala Omelette', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D353', 'Masala Poha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D354', 'Masala Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D355', 'Masala Puri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D356', 'Masala Uttapam', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D357', 'Masale Bhat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D358', 'Mashroom Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D359', 'Mashroom Mutter Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D360', 'Masoor Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D361', 'Masoor Dal Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D362', 'Masoor Ki Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D363', 'Matki Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D364', 'Matki Usal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D365', 'Matki Ussal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D366', 'Medu Vada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D367', 'Medu Wada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D368', 'Meduwada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D369', 'Mehsoor Idli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D370', 'Methi Chaman', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D371', 'Methi Chana Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D372', 'Methi Chawan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D373', 'Methi Lasooni Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D374', 'Methi Malai Mutter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D375', 'Methi Matar Malai', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D376', 'Methi Moong Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D377', 'Methi Moong Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D378', 'Methi Muthia', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D379', 'Methi Mutter Malai', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D380', 'Methi Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D381', 'Methi Thepla', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D382', 'Milk', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D383', 'Mint Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D384', 'Mint Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D385', 'Mint Yogurt', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D386', 'Mirch Ka Salan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D387', 'Mirchi Ka Salan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D388', 'Misal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D389', 'Misal Pav', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D390', 'Missal Pav', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D391', 'Missi Roti', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D392', 'Mix Cut Fruits', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D393', 'Mix Dal Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D394', 'Mix Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D395', 'Mix Sprout Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D396', 'Mix Sprouts Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D397', 'Mix Usal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D398', 'Mix Veg', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D399', 'Mix Veg Biryani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D400', 'Mix Veg Combination Fried Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D401', 'Mix Veg Cutlets', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D402', 'Mix Veg Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D403', 'Mix Veg Fried Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D404', 'Mix Veg Hakka Noodles', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D405', 'Mix Veg Hakka Noodles Tossed With Schezwan Sauce', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D406', 'Mix Veg Kolhapuri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D407', 'Mix Veg Kurma', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D408', 'Mix Veg Maggi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D409', 'Mix Veg Maggie', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D410', 'Mix Veg Maratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D411', 'Mix Veg Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D412', 'Mix Veg Raita', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D413', 'Mix Veg Rawa Upama', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D414', 'Mix Veg Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D415', 'Mix Veg Tawa Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D416', 'Mixed Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D417', 'Mixed Vegetable Poriyal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D418', 'Mogar Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D419', 'Moog Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D420', 'Moong', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D421', 'Moong Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D422', 'Moong Dal Bhajji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D423', 'Moong Dal Chilka (Green Split)', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D424', 'Moong Dal Chilla', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D425', 'Moong Dal Methi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D426', 'Moong Dal Paysam', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D427', 'Moong Masoor Dal Tarka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D428', 'Moong Sprouted Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D429', 'Moong Ussal Rassa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D430', 'Moongachi Usal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D431', 'Motichoor Laddu', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D432', 'Motichur Laddu', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D433', 'Murgh Hariyali', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D434', 'Murgh Makhani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D435', 'Mushroom Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D436', 'Mutter Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D437', 'Mutter Ka Salan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D438', 'Nargisi Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D439', 'Nawabi Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D440', 'Omelette Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D441', 'Omelette Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D442', 'Onion', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D443', 'Onion Bhaji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D444', 'Onion Brown Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D445', 'Onion Chop', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D446', 'Onion Cubes Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D447', 'Onion Lemon', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D448', 'Onion Pakoras', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D449', 'Onion Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D450', 'Onion Tadka Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D451', 'Onion Uttapam', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D452', 'Padwal Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D453', 'Pahadi Chicken Curry', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D454', 'Pakoda', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D455', 'Palak Corn', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D456', 'Palak Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D457', 'Palak Kofta Green Gravy', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D458', 'Palak Lasooni', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D459', 'Palak Mushroom Baby Corn Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D460', 'Palak Paneer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D461', 'Palak Puri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D462', 'Panchameli Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D463', 'Pancharatna Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D464', 'Panchmel Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D465', 'Paneer Bhaji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D466', 'Paneer Bhurji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D467', 'Paneer Bhurji Wrap', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D468', 'Paneer Changezi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D469', 'Paneer Chettinad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D470', 'Paneer Chilli Gravy', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D471', 'Paneer Do Pyaza', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D472', 'Paneer Gavran', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D473', 'Paneer Hariyali', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D474', 'Paneer Hyderabadi Biryani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D475', 'Paneer Kadhai Franky', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D476', 'Paneer Ke Kofte In Makhani Gravy', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D477', 'Paneer Khurchan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D478', 'Paneer Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D479', 'Paneer Lababdar', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D480', 'Paneer Lahori', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D481', 'Paneer Madras Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D482', 'Paneer Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D483', 'Paneer Mughlai', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D484', 'Paneer Mutter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D485', 'Paneer Mutter Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D486', 'Paneer Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D487', 'Paneer Tikka Biryani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D488', 'Paneer Tikka Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D489', 'Paneer Tikka Rolls', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D490', 'Panzanela Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D491', 'Papad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D492', 'Papad Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D493', 'Papadi Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D494', 'Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D495', 'Pasta Live Counter', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D496', 'Pat Vadi Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D497', 'Pattice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D498', 'Pav', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D499', 'Pav Bhaji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D500', 'Peanut Aloo Poha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D501', 'Peanut Curd Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D502', 'Peanut Poha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D503', 'Peanuts and Potato Poha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D504', 'Phodani Bhaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D505', 'Phulka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D506', 'Pickle', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D507', 'Pindi Chana Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D508', 'Pindi Chole', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D509', 'Pineapple Curd', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D510', 'Pineapple Sheera', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D511', 'Plain Curd', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D512', 'Plain Masoor Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D513', 'Plain Moong Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D514', 'Poha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D515', 'Poha Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D516', 'Pomegranate Curd', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D517', 'Pomegranate Raita', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D518', 'Poola', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D519', 'Pulaka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D520', 'Pulav', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D521', 'Punjabi Chole', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D522', 'Punjabi Dum Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D523', 'Puri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D524', 'Raddish & Aloo Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D525', 'Ragda Pattice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D526', 'Rajasthani Dahi Kadi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D527', 'Rajasthani Pakoda Kadhi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D528', 'Rajma Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D529', 'Rara Chicken', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D530', 'Rawa Kheer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D531', 'Rawa Ladoo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D532', 'Red & White Sauce', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D533', 'Red Masoor Dal Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D534', 'Red Thai Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D535', 'Regular Coffee', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D536', 'Regular Tea', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D537', 'Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D538', 'Rice Kheer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D539', 'Rice Papad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D540', 'Roasted Veggies & Rajma Quesadilla', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D541', 'Sabudana Khichdi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D542', 'Sabudana Vada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D543', 'Sabudana Wada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D544', 'Sago Kheer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D545', 'Salad Bar', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D546', 'Salan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D547', 'Salted Lassi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D548', 'Sambar', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D549', 'Sambhar', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D550', 'Samosa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D551', 'Samosa Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D552', 'Sauté Vegetable', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D553', 'Sev', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D554', 'Sev Bhaji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D555', 'Sev Ki Sabzi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D556', 'Sevai Upma', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D557', 'Sezwan Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D558', 'Shahi Tukda', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D559', 'Shahi Tukra', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D560', 'Sham Sayera (Palak Paneer Kofta)', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D561', 'Sheera', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D562', 'Shevai Kheer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D563', 'Shezwan Noodles', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D564', 'Sindhi Kadi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D565', 'Slice Cucumber', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D566', 'Slice Tomato, Cucumber', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D567', 'Slice Tomato, Cucumber, Lettuce, Onion', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D568', 'Small Cube Cut Carrot, Tomato, Beetroot, Onion', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D569', 'Sour Sauce', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D570', 'Soy Manchurian Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D571', 'Soya Chams Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D572', 'Soya Chunks Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D573', 'Soya Dum', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D574', 'Soya Ghashi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D575', 'Soya Green Peas Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D576', 'Soya Keema', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D577', 'Soya Kheema', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D578', 'Soya Masal Malwani Style', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D579', 'Soya Masala Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D580', 'Soya Masala Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D581', 'Soya Mutter Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D582', 'Soya Mutter Sabji', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D583', 'Spicy Tomato Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D584', 'Split Moong Dal Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D585', 'Sprouted Matki Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D586', 'Sprouted Moong Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D587', 'Sprouted Moong Ussal Rassa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D588', 'Sprouted Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D589', 'Sprouts & American Corn Chaat', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D590', 'Sprouts Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D591', 'Steam Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D592', 'Stick Carrot, Cucumber', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D593', 'Stick Carrot, Cucumber, Radish, Beetroot', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D594', 'Stick Carrot, Cucumber, Reddish, Beetroot', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D595', 'Stick Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D596', 'Suji Sheera', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D597', 'Sweet Chutney', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D598', 'Tabouleh Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D599', 'Tadka Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D600', 'Tadka Yogurt', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D601', 'Tadkewali Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D602', 'Tandoori Lachha Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D603', 'Tandoori Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D604', 'Tawa Butter Kulcha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D605', 'Tawa Paratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D606', 'Tawa Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D607', 'Tawa Veg', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D608', 'Tea', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D609', 'Tendli Chana Sukka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D610', 'Tendli Channa', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D611', 'Tendli Channa Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D612', 'Tendli Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D613', 'Thai Curry Green', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D614', 'Toasted Bombay Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D615', 'Tomato Ketchup', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D616', 'Tomato Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D617', 'Toor Dal Tadka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D618', 'Tosad Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D619', 'Toss Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D620', 'Toss Salad With South Ka Tadka', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D621', 'Tossed Salad', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D622', 'Triveni Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D623', 'Tuar Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D624', 'Turai Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D625', 'Turai Moong Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D626', 'Upma', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D627', 'Urad Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D628', 'Uttapam', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D629', 'Vada Pav', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D630', 'Vangyache Bharit', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D631', 'Varan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D632', 'Vatana Ussal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D633', 'Veg Bhuna', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D634', 'Veg Bhuna Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D635', 'Veg Chatinal Bryani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D636', 'Veg Chutney Sandwich', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D637', 'Veg Fried Rice Sezwan', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D638', 'Veg Fry Rice', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D639', 'Veg Hakka Noodles', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D640', 'Veg Handi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D641', 'Veg Jalfraji Dry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D642', 'Veg Jalfrezi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D643', 'Veg Kadhai', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D644', 'Veg Keema Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D645', 'Veg Khada', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D646', 'Veg Kofta Curry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D647', 'Veg Kolhapuri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D648', 'Veg Kurma', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D649', 'Veg Lahori', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D650', 'Veg Lasagne', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D651', 'Veg Maharaja', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D652', 'Veg Makhanwala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D653', 'Veg Maratha', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D654', 'Veg Masala Khichdi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D655', 'Veg Paneer Biryani', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D656', 'Veg Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D657', 'Veg Schezwan Hakka Noodles', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D658', 'Veg Upma', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D659', 'Veg Yakhni Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D660', 'Vegetable Jaipuri', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D661', 'Vegetable Maggi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D662', 'Vegetarian Pasta', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D663', 'Vegetarian Pulao', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D664', 'Veggies & Rajma Quesadilla', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D665', 'Vermicelli Kheer', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D666', 'Vermicelli Upama', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D667', 'Vermicelli Upma', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D668', 'Vermicil Upama', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D669', 'Vilayati Veg', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D670', 'Wada Pav', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D671', 'Wal Papadi', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D672', 'Wheat Flakes', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D673', 'White Bread/Brown Bread', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D674', 'White Vatana Ussal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D675', 'Whole Moong Dal', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D676', 'Whole Moong Masala', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D677', 'Yellow Dal Fry', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D678', 'Yellow Moong Dal', 'Veg');