-- Create the Dishes table
CREATE TABLE Dishes (
    dish_id VARCHAR(4) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Meal_Category ENUM('Veg', 'Non-Veg', 'Jain') NOT NULL
);

-- Insert data for all 84 dishes
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES
('D001', 'Aloo Gobi', 'Veg'),
('D002', 'Palak Paneer', 'Veg'),
('D003', 'Bhindi Masala', 'Veg'),
('D004', 'Baingan Bharta', 'Veg'),
('D005', 'Matar Paneer', 'Veg'),
('D006', 'Gobi Manchurian', 'Veg'),
('D007', 'Chana Masala', 'Veg'),
('D008', 'Jeera Aloo', 'Veg'),
('D009', 'Mushroom Masala', 'Veg'),
('D010', 'Dum Aloo', 'Veg'),
('D011', 'Kadai Paneer', 'Veg'),
('D012', 'Aloo Matar', 'Veg'),
('D013', 'Shahi Paneer', 'Veg'),
('D014', 'Methi Malai Matar', 'Veg'),
('D015', 'Tawa Sabzi', 'Veg'),
('D016', 'Aloo Palak', 'Veg'),
('D017', 'Kaddu ki Sabzi', 'Veg'),
('D018', 'Lauki ki Sabzi', 'Veg'),
('D019', 'Green Beans Sabzi', 'Veg'),
('D020', 'Cabbage Sabzi', 'Veg'),
('D021', 'Tinda Masala', 'Veg'),
('D022', 'Karela Masala', 'Veg'),
('D023', 'Arbi Masala', 'Jain'),
('D024', 'Raw Banana Sabzi', 'Veg'),
('D025', 'Suran Masala', 'Jain'),
('D026', 'Jain Bhindi Sabzi', 'Jain'),
('D027', 'Jain Matar Sabzi', 'Jain'),
('D028', 'Jain Paneer Sabzi', 'Jain'),
('D029', 'Jain Gobi Sabzi', 'Jain'),
('D030', 'Jain Pumpkin Sabzi', 'Jain'),
('D031', 'Dal Makhani', 'Veg'),
('D032', 'Moong Dal Fry', 'Veg'),
('D033', 'Chana Dal Tadka', 'Veg'),
('D034', 'Masoor Dal', 'Veg'),
('D035', 'Rajma Masala', 'Veg'),
('D036', 'Jain Dal Fry', 'Jain'),
('D037', 'Chicken Biryani', 'Non-Veg'),
('D038', 'Vegetable Pulao', 'Veg'),
('D039', 'Jeera Rice', 'Veg'),
('D040', 'Lemon Rice', 'Veg'),
('D041', 'Jain Veg Biryani', 'Jain'),
('D042', 'Chole Bhature', 'Veg'),
('D043', 'Butter Chicken', 'Non-Veg'),
('D044', 'Rogan Josh', 'Non-Veg'),
('D045', 'Fish Curry', 'Non-Veg'),
('D046', 'Prawn Masala', 'Non-Veg'),
('D047', 'Naan', 'Veg'),
('D048', 'Paratha', 'Veg'),
('D049', 'Roti', 'Veg'),
('D050', 'Kulcha', 'Veg'),
('D051', 'Rasam', 'Veg'),
('D052', 'Kheer', 'Veg'),
('D053', 'Gulab Jamun', 'Veg'),
('D054', 'Jalebi', 'Veg'),
('D055', 'Dosa', 'Veg'),
('D056', 'Fruit Platter', 'Veg'),
('D057', 'Jain Poha', 'Jain'),
('D058', 'Eggs', 'Non-Veg'),
('D059', 'Samosa', 'Veg'),
('D060', 'Aloo Tikki Chaat', 'Veg'),
('D061', 'Pakora', 'Veg'),
('D062', 'Dhokla', 'Veg'),
('D063', 'Fruit Chaat', 'Veg'),
('D064', 'Khaman', 'Veg'),
('D065', 'Jain Kachori', 'Jain'),
('D066', 'Tea', 'Veg'),
('D067', 'Coffee', 'Veg'),
('D068', 'Idli', 'Veg'),
('D069', 'Sambar', 'Veg'),
('D070', 'Puri', 'Veg'),
('D071', 'Poha', 'Veg'),
('D072', 'Upma', 'Veg'),
('D073', 'Dal Tadka', 'Veg'),
('D074', 'Kadhi', 'Veg'),
('D075', 'Salad', 'Veg'),
('D076', 'Omelette', 'Non-Veg'),
('D077', 'Medu Vada', 'Veg'),
('D078', 'Chapati', 'Veg'),
('D079', 'Vada Pav', 'Veg'),
('D080', 'Dal Bukhara', 'Veg'),
('D081', 'Paneer Jalfrezi', 'Veg'),
('D082', 'Turai Moong Dry', 'Veg'),
('D083', 'Steamed Rice', 'Veg'),
('D084', 'Gatte ki Sabji', 'Veg');