-- Create the Ingredients table
CREATE TABLE Ingredients (
    ingredient_id VARCHAR(4) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Meal_Category ENUM('Veg', 'Non-Veg', 'Jain') NOT NULL
);

INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I001', 'Almonds', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I002', 'Anardana powder', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I003', 'Apple', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I004', 'Baby corn', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I005', 'Baby potato', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I006', 'Baking powder', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I007', 'Banana', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I008', 'Bay leaf', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I009', 'Beans', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I010', 'Beetroot', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I011', 'Besan', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I012', 'Bhindi', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I013', 'Black chana', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I014', 'Black pepper', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I015', 'Black-eyed peas', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I016', 'Boondi', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I017', 'Bread', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I018', 'Bread crumbs', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I019', 'Brinjal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I020', 'Broken wheat', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I021', 'Brown rice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I022', 'Bulgar wheat', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I023', 'Butter', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I024', 'Cabbage', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I025', 'Capsicum', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I026', 'Cardamom', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I027', 'Carrot', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I028', 'Cashew nuts', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I029', 'Cashew paste', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I030', 'Cauliflower', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I031', 'Chaat masala', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I032', 'Chana dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I033', 'Chana masala', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I034', 'Chana sprouts', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I035', 'Chenna', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I036', 'Chicken', 'Non-Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I037', 'Chickpeas', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I038', 'Cinnamon', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I039', 'Cloves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I040', 'Coconut', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I041', 'Coconut milk', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I042', 'Coffee powder', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I043', 'Coriander leaves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I044', 'Coriander powder', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I045', 'Coriander seeds', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I046', 'Corn', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I047', 'Corn cob', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I048', 'Corn flakes', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I049', 'Cornflour', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I050', 'Crab meat', 'Non-Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I051', 'Cream', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I052', 'Cucumber', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I053', 'Cumin powder', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I054', 'Cumin seeds', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I055', 'Curd', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I056', 'Curry leaves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I057', 'Custard powder', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I058', 'Dabeli masala', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I059', 'Dalia', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I060', 'Doodhi', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I061', 'Dried green peas', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I062', 'Dried white peas', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I063', 'Drumstick', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I064', 'Dry red chili', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I065', 'Egg', 'Non-Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I066', 'Eggplant', 'Non-Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I067', 'Eno', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I068', 'Fennel seeds', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I069', 'Fenugreek leaves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I070', 'Fruit jam', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I071', 'Garam masala', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I072', 'Garlic', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I073', 'Gavar', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I074', 'Gawar', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I075', 'Ghee', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I076', 'Ginger', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I077', 'Green beans', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I078', 'Green black-eyed peas', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I079', 'Green chili', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I080', 'Green chutney', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I081', 'Green curry paste', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I082', 'Green moong dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I083', 'Green moong sprouts', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I084', 'Green peas', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I085', 'Hakka noodles', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I086', 'Honey', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I087', 'Ice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I088', 'Idli', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I089', 'Karela', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I090', 'Khoya', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I091', 'Kiwi', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I092', 'Lauki', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I093', 'Lemon', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I094', 'Lemon juice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I095', 'Lettuce', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I096', 'Macaroni', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I097', 'Maggi masala', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I098', 'Maggi noodles', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I099', 'Maida', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I100', 'Mango juice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I101', 'Masoor dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I102', 'Matki', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I103', 'Matki sprouts', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I104', 'Mayonnaise', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I105', 'Methi leaves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I106', 'Milk', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I107', 'Minced chicken', 'Non-Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I108', 'Mint chutney', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I109', 'Mint leaves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I110', 'Moong dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I111', 'Mushroom', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I112', 'Mustard oil', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I113', 'Mustard seeds', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I114', 'Navy beans', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I115', 'Oil', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I116', 'Onion', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I117', 'Orange juice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I118', 'Paneer', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I119', 'Papad', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I120', 'Papadi', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I121', 'Papaya', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I122', 'Papdi', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I123', 'Parsley', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I124', 'Pasta', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I125', 'Pav', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I126', 'Pav bhaji masala', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I127', 'Peanut paste', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I128', 'Peanuts', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I129', 'Pickle', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I130', 'Pickled vegetables', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I131', 'Pineapple', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I132', 'Pineapple juice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I133', 'Poha', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I134', 'Pomegranate seeds', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I135', 'Potato', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I136', 'Puffed rice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I137', 'Radish', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I138', 'Raisins', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I139', 'Rajma', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I140', 'Red cabbage', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I141', 'Red chili powder', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I142', 'Red curry paste', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I143', 'Rice', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I144', 'Rice flour', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I145', 'Ridge gourd', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I146', 'Sabudana', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I147', 'Saffron', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I148', 'Salt', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I149', 'Sambar masala', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I150', 'Samosa', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I151', 'Schezwan sauce', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I152', 'Semolina', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I153', 'Sev', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I154', 'Snake gourd', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I155', 'Soya chunks', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I156', 'Soya granules', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I157', 'Soya sauce', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I158', 'Spinach', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I159', 'Split green moong dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I160', 'Spring onion', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I161', 'Sugar', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I162', 'Tamarind', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I163', 'Tamarind chutney', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I164', 'Tamarind paste', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I165', 'Tea leaves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I166', 'Tendli', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I167', 'Tomato', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I168', 'Toor dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I169', 'Tulsi leaves', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I170', 'Turmeric', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I171', 'Urad dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I172', 'Vada', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I173', 'Vermicelli', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I174', 'Vinegar', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I175', 'Water', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I176', 'Watermelon', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I177', 'Wheat flakes', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I178', 'Wheat flour', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I179', 'Whole masoor dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I180', 'Yellow moong dal', 'Veg');
INSERT INTO Ingredients (ingredient_id, Name, Meal_Category) VALUES ('I181', 'Yogurt', 'Veg');