
CREATE TABLE IF NOT EXISTS Dishes (
    dish_id VARCHAR(4) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Meal_Category VARCHAR(10) NOT NULL
);

INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES
('D001', 'Corn Flakes', 'Veg'),
('D002', 'Butter', 'Veg'),
('D003', 'Jam', 'Veg'),
('D004', 'Bread (Brown/White Option)', 'Veg'),
('D005', 'Milk', 'Veg'),
('D006', 'Tea', 'Veg'),
('D007', 'Coffee', 'Veg'),
('D008', 'Onion Salad', 'Veg'),
('D009', 'Omelette', 'Non-Veg'),
('D010', 'Malvani Chicken Curry', 'Non-Veg'),
('D011', 'Malvani Paneer Curry', 'Veg'),
('D012', 'Steam Rice', 'Veg'),
('D013', 'Chapati', 'Veg'),
('D014', 'Dal Fry', 'Veg'),
('D015', 'Papad', 'Veg'),
('D016', 'Pickle', 'Veg'),
('D017', 'Bambaya Murmura Bhel', 'Veg'),
('D018', 'Green Chutney', 'Veg'),
('D019', 'Imli Chutney', 'Veg'),
('D020', 'Julienne Salad', 'Veg'),
('D021', 'Chawli Masala', 'Veg'),
('D022', 'Capsicum Aloo Dry', 'Veg'),
('D023', 'Masala Dal', 'Veg'),
('D024', 'Phulka', 'Veg'),
('D025', 'Jalebi', 'Veg'),
('D026', 'Aloo Paratha', 'Veg'),
('D027', 'Curd', 'Veg'),
('D028', 'Cut Fruit', 'Veg'),
('D029', 'Dum Aloo Punjabi', 'Veg'),
('D030', 'Dahi Kadi', 'Veg'),
('D031', 'Tadka Rice', 'Veg'),
('D032', 'Pakoda', 'Veg'),
('D033', 'Chilli Soya', 'Veg'),
('D034', 'Kimchi Salad', 'Non-Veg'),
('D035', 'Gobi Aloo Dry', 'Veg'),
('D036', 'Palak Mushroom Baby Corn Masala', 'Veg'),
('D037', 'Dal Makhani', 'Veg'),
('D038', 'Brown Onion Rice', 'Veg'),
('D039', 'Carrot Kheer', 'Veg'),
('D040', 'Bombay Sandwich', 'Veg'),
('D041', 'Eggs Fry', 'Non-Veg'),
('D042', 'Beet Salad', 'Veg'),
('D043', 'Cabbage Channa Dry', 'Veg'),
('D044', 'Rajma Masala', 'Veg'),
('D045', 'Dal Tadka', 'Veg'),
('D046', 'Jeera Rice', 'Veg'),
('D047', 'Buttermilk', 'Veg'),
('D048', 'Butter Corn', 'Veg'),
('D049', 'Carrot/Cucumber Salad', 'Veg'),
('D050', 'Palak Paneer', 'Veg'),
('D051', 'Chicken Kolhapuri', 'Non-Veg'),
('D052', 'Plain Moong Dal', 'Veg'),
('D053', 'Mix Veg Rawa Upama', 'Veg'),
('D054', 'Masala Poha', 'Veg'),
('D055', 'Coconut Chutney', 'Veg'),
('D056', 'Green Salad', 'Veg'),
('D057', 'Macroni (Maggi Masala Indian Style)', 'Veg'),
('D058', 'Soya Masala Dry', 'Veg'),
('D059', 'Carrots Rice', 'Veg'),
('D060', 'Wada Pav', 'Veg'),
('D061', 'Mix Veg Salad', 'Veg'),
('D062', 'Mix Veg Karela', 'Veg'),
('D063', 'Aloo Dry', 'Veg'),
('D064', 'Dal Trivani', 'Veg'),
('D065', 'Tomato Rice', 'Veg'),
('D066', 'Missi Roti', 'Veg'),
('D067', 'Jeera Aloo', 'Veg'),
('D068', 'Bread', 'Veg'),
('D069', 'Moong Sprout Salad', 'Veg'),
('D070', 'Gwar Fali Ki Sabji', 'Veg'),
('D071', 'Aloo Mutter', 'Veg'),
('D072', 'Green Dal Moog', 'Veg'),
('D073', 'Koshimbir Salad', 'Veg'),
('D074', 'Lemon', 'Veg'),
('D075', 'Pav Bhaji', 'Veg'),
('D076', 'Tawa Pulao', 'Veg'),
('D077', 'Pav', 'Veg'),
('D078', 'Egg Bhurji', 'Non-Veg'),
('D079', 'Paneer Bhurji', 'Veg'),
('D080', 'Tawa Paratha', 'Veg'),
('D081', 'Baingan Masala', 'Veg'),
('D082', 'Akha Masoor', 'Veg'),
('D083', 'Masale Bhat', 'Veg'),
('D084', 'Mix Veg Raita', 'Veg'),
('D085', 'Channa Chaat', 'Veg'),
('D086', 'Tossed Salad', 'Veg'),
('D087', 'Nargisi Kofta Curry', 'Non-Veg'),
('D088', 'Malavani Eggs Curry', 'Non-Veg'),
('D089', 'Moong Dal', 'Veg'),
('D090', 'Gulab Jamun', 'Veg'),
('D091', 'Macroni', 'Veg'),
('D092', 'Soya Masala', 'Veg'),
('D093', 'Aloo', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D094', 'Bhatura', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D095', 'Bhindi Do Pyaaza', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D096', 'Boondi Raita', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D097', 'Chole', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D098', 'Eggs To Order', 'Non-Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D099', 'Idli', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D100', 'Sambhar', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D101', 'Vermicelli Upama', 'Veg');
INSERT INTO Dishes (dish_id, Name, Meal_Category) VALUES ('D102', 'Poha', 'Veg');