
CREATE TABLE IF NOT EXISTS Ingredients (
    Ingredient_id VARCHAR(5) PRIMARY KEY,
    Ingredient_name VARCHAR(100) NOT NULL,
    Meal_Category VARCHAR(10) NOT NULL
);

INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES
('I001', 'Corn Flakes', 'Veg'),
('I002', 'Butter', 'Veg'),
('I003', 'Jam', 'Veg'),
('I004', 'Bread', 'Veg'),
('I005', 'Milk', 'Veg'),
('I006', 'Tea leaves', 'Veg'),
('I007', 'Water', 'Veg'),
('I008', 'Coffee grounds', 'Veg'),
('I009', 'Onions', 'Veg'),
('I010', 'Green chilies', 'Veg'),
('I011', 'Coriander leaves', 'Veg'),
('I012', 'Lemon juice', 'Veg'),
('I013', 'Salt', 'Veg'),
('I014', 'Chaat masala', 'Veg'),
('I015', 'Eggs', 'Non-Veg'),
('I016', 'Cheese', 'Veg'),
('I017', 'Cherry tomatoes', 'Veg'),
('I018', 'Herbs', 'Veg'),
('I019', 'Chicken', 'Non-Veg'),
('I020', 'Tomatoes', 'Veg'),
('I021', 'Coconut', 'Veg'),
('I022', 'Malvani masala', 'Veg'),
('I023', 'Red chili powder', 'Veg'),
('I024', 'Turmeric powder', 'Veg'),
('I025', 'Oil', 'Veg'),
('I026', 'Paneer', 'Veg'),
('I027', 'Black cardamom', 'Veg'),
('I028', 'Green cardamom', 'Veg'),
('I029', 'Cloves', 'Veg'),
('I030', 'Dried red chilies', 'Veg'),
('I031', 'Coriander seeds', 'Veg'),
('I032', 'Cumin seeds', 'Veg'),
('I033', 'Stone flower', 'Veg'),
('I034', 'Cinnamon', 'Veg'),
('I035', 'Ginger-garlic paste', 'Veg'),
('I036', 'Dried coconut', 'Veg'),
('I037', 'Tomato', 'Veg'),
('I038', 'Star anise', 'Veg'),
('I039', 'Curry leaves', 'Veg'),
('I040', 'Coconut milk', 'Veg'),
('I041', 'Rice', 'Veg'),
('I042', 'Whole wheat flour', 'Veg'),
('I043', 'Toor dal', 'Veg'),
('I044', 'Onion', 'Veg'),
('I045', 'Green chili', 'Veg'),
('I046', 'Ginger', 'Veg'),
('I047', 'Garlic', 'Veg'),
('I048', 'Coriander powder', 'Veg'),
('I049', 'Garam masala', 'Veg'),
('I050', 'Papad', 'Veg'),
('I051', 'Pickle', 'Veg'),
('I052', 'Murmura', 'Veg'),
('I053', 'Tamarind chutney', 'Veg'),
('I054', 'Green chutney', 'Veg'),
('I055', 'Mint leaves', 'Veg'),
('I056', 'Tamarind', 'Veg'),
('I057', 'Jaggery', 'Veg'),
('I058', 'Cumin powder', 'Veg'),
('I059', 'Carrot', 'Veg'),
('I060', 'Cucumber', 'Veg'),
('I061', 'Capsicum', 'Veg'),
('I062', 'Black pepper', 'Veg'),
('I063', 'Chawli', 'Veg'),
('I064', 'Potato', 'Veg'),
('I065', 'Moong dal', 'Veg'),
('I066', 'Masoor dal', 'Veg'),
('I067', 'Besan', 'Veg'),
('I068', 'Sugar', 'Veg'),
('I069', 'Water for syrup', 'Veg'),
('I070', 'Saffron', 'Veg'),
('I071', 'Cardamom powder', 'Veg'),
('I072', 'Wheat Flour', 'Veg'),
('I073', 'Green Chilli', 'Veg'),
('I074', 'Coriander Leaves', 'Veg'),
('I075', 'Chaat Masala', 'Veg'),
('I076', 'Bhaja Masala', 'Veg'),
('I077', 'Ajwain', 'Veg'),
('I078', 'Curd', 'Veg'),
('I079', 'Mixed Seasonal Fruits', 'Veg'),
('I080', 'Tea Leaves', 'Veg'),
('I081', 'Cardamom', 'Veg'),
('I082', 'Instant Coffee Powder', 'Veg'),
('I083', 'Hot Water', 'Veg'),
('I084', 'Cabbage', 'Veg'),
('I085', 'Lemon Juice', 'Veg'),
('I086', 'Black Pepper', 'Veg'),
('I087', 'Baby Potatoes', 'Veg'),
('I088', 'Tomato Puree', 'Veg'),
('I089', 'Ginger Garlic Paste', 'Veg'),
('I090', 'Cashew Paste', 'Veg'),
('I091', 'Cumin Seeds', 'Veg'),
('I092', 'Turmeric Powder', 'Veg'),
('I093', 'Red Chilli Powder', 'Veg'),
('I094', 'Coriander Powder', 'Veg'),
('I095', 'Ging', 'Veg'),
('I096', 'Curry Leaves', 'Veg'),
('I097', 'Mustard Seeds', 'Veg'),
('I098', 'Asafoetida', 'Veg'),
('I099', 'Toor Dal', 'Veg'),
('I100', 'Garam Masala', 'Veg'),
('I101', 'Cooked Rice', 'Veg'),
('I102', 'Mint Leaves', 'Veg'),
('I103', 'Green Cardamom', 'Veg'),
('I104', 'Cinnamon Stick', 'Veg'),
('I105', 'Mixed Vegetable Pickle', 'Veg'),
('I106', 'Soya Chunks', 'Veg'),
('I107', 'Soy Sauce', 'Veg'),
('I108', 'Red Chilli Sauce', 'Veg'),
('I109', 'Tomato Ketchup', 'Veg'),
('I110', 'Cornflour', 'Veg'),
('I111', 'Radish', 'Veg'),
('I112', 'Spring Onion', 'Veg'),
('I113', 'Red Chilli Flakes', 'Veg'),
('I114', 'Fish Sauce', 'Non-Veg'),
('I115', 'Cauliflower', 'Veg'),
('I116', 'Spinach', 'Veg'),
('I117', 'Mushroom', 'Veg'),
('I118', 'Baby Corn', 'Veg'),
('I119', 'Whole Black Urad Dal', 'Veg'),
('I120', 'Rajma', 'Veg'),
('I121', 'Cream', 'Veg'),
('I122', 'Cooked Basmati Rice', 'Veg'),
('I123', 'Bay Leaf', 'Veg'),
('I124', 'Cardamom Powder', 'Veg'),
('I125', 'Ghee', 'Veg'),
('I126', 'Cashew Nuts', 'Veg'),
('I127', 'Raisins', 'Veg'),
('I128', 'Green Chutney', 'Veg'),
('I129', 'Beetroot', 'Veg'),
('I130', 'Salad Greens', 'Veg'),
('I131', 'Shallot', 'Veg'),
('I132', 'Green Apple', 'Veg'),
('I133', 'Walnuts', 'Veg'),
('I134', 'Goat Cheese', 'Veg'),
('I135', 'Balsamic Vinaigrette', 'Veg'),
('I136', 'Olive Oil', 'Veg'),
('I137', 'Chickpeas', 'Veg'),
('I138', 'Green Peas', 'Veg'),
('I139', 'Moong Dal', 'Veg'),
('I140', 'Chana Dal', 'Veg'),
('I141', 'Basmati Rice', 'Veg'),
('I142', 'Cumin Powder', 'Veg'),
('I143', 'Corn Kernels', 'Veg'),
('I144', 'Honey', 'Veg'),
('I145', 'Green Onion', 'Veg'),
('I146', 'Chili Oil', 'Veg'),
('I147', 'Sesame Oil', 'Veg'),
('I148', 'Rice Vinegar', 'Veg'),
('I149', 'Sesame Seeds', 'Veg'),
('I150', 'Kolhapuri Masala', 'Veg'),
('I151', 'Rava', 'Veg'),
('I152', 'Oil or ghee', 'Veg'),
('I153', 'Mustard seeds', 'Veg'),
('I154', 'Urad dal', 'Veg'),
('I155', 'Chana dal', 'Veg'),
('I156', 'Peanuts', 'Veg'),
('I157', 'Cashews', 'Veg'),
('I158', 'Mixed vegetables (carrots, beans, peas)', 'Veg'),
('I159', 'Poha', 'Veg'),
('I160', 'Mixed vegetables (carrots, peas, etc.)', 'Veg'),
('I161', 'Coriander seeds powder', 'Veg'),
('I162', 'Cumin seeds powder', 'Veg'),
('I163', 'Garam masala powder', 'Veg'),
('I164', 'Grated coconut', 'Veg'),
('I165', 'Shallots', 'Veg'),
('I166', 'Red chillies', 'Veg'),
('I167', 'Tamarind paste', 'Veg'),
('I168', 'Hing', 'Veg'),
('I169', 'Garlic (for tempering)', 'Veg'),
('I170', 'Red chili (for tempering)', 'Veg'),
('I171', 'Bread slices', 'Veg'),
('I172', 'Instant coffee', 'Veg'),
('I173', 'Mixed greens', 'Veg'),
('I174', 'Avocado', 'Veg'),
('I175', 'Goat cheese', 'Veg'),
('I176', 'Red onion', 'Veg'),
('I177', 'Fresh herbs (like coriander or mint)', 'Veg'),
('I178', 'Macaroni', 'Veg'),
('I179', 'Peas', 'Veg'),
('I180', 'Maggi Magic Masala', 'Veg'),
('I181', 'Ketchup', 'Veg'),
('I182', 'Soya chunks', 'Veg'),
('I183', 'Green chillies', 'Veg'),
('I184', 'Ginger garlic paste', 'Veg'),
('I185', 'Turmeric', 'Veg'),
('I186', 'Basmati rice', 'Veg'),
('I187', 'Yogurt', 'Veg'),
('I188', 'Black salt', 'Veg'),
('I189', 'Roasted cumin powder', 'Veg'),
('I190', 'Black pepper powder', 'Veg'),
('I191', 'Ice cubes', 'Veg'),
('I192', 'Potatoes', 'Veg'),
('I193', 'Besan (chickpea flour)', 'Veg'),
('I194', 'Turmeric (for batter)', 'Veg'),
('I195', 'Red chili powder (for batter)', 'Veg'),
('I196', 'Salt (for batter)', 'Veg'),
('I197', 'Pav (Indian buns)', 'Veg'),
('I198', 'Dry garlic chutney', 'Veg'),
('I199', 'Chat masala', 'Veg'),
('I200', 'Bitter gourd (karela)', 'Veg'),
('I201', 'Gram Flour', 'Veg'),
('I202', 'Chilli', 'Veg'),
('I203', 'Kasuri Methi', 'Veg'),
('I204', 'Mango Powder', 'Veg'),
('I205', 'Coffee Powder', 'Veg'),
('I206', 'Moong Sprouts', 'Veg'),
('I207', 'Roasted Peanuts', 'Veg'),
('I208', 'Cluster Beans', 'Veg'),
('I209', 'Vegetable Pickle', 'Veg'),
('I210', 'Lemon', 'Veg'),
('I211', 'Pav Bhaji Masala', 'Veg'),
('I212', 'Pav', 'Veg'),
('I213', 'Lettuce', 'Veg'),
('I214', 'Brinjal', 'Veg'),
('I215', 'Masoor Dal', 'Veg'),
('I216', 'Meat', 'Veg'),
('I217', 'Malvani Masala', 'Veg'),
('I218', 'Coconut Milk', 'Veg'),
('I219', 'Khoya', 'Veg'),
('I220', 'Maida', 'Veg'),
('I221', 'Baking Soda', 'Veg'),
('I222', 'Rose Water', 'Veg'),
('I223', 'Rawa', 'Veg'),
('I224', 'Vegetables', 'Veg'),
('I225', 'Garlic for tempering', 'Veg'),
('I226', 'Red chili for tempering', 'Veg'),
('I227', 'Coffee', 'Veg'),
('I228', 'Greens', 'Veg'),
('I229', 'Fresh herbs', 'Veg'),
('I230', 'Chillies', 'Veg'),
('I231', 'Wheat flour', 'Veg'),
('I232', 'Turmeric for batter', 'Veg'),
('I233', 'Red chili powder for batter', 'Veg'),
('I234', 'Salt for batter', 'Veg'),
('I235', 'Chutney', 'Veg'),
('I236', 'Garlic chutney', 'Veg'),
('I237', 'Bitter gourd', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I300', 'Bhatura Dough', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I301', 'Bhindi', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I302', 'Curd', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I303', 'Boondi', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I304', 'Chole (Chickpeas)', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I305', 'Eggs', 'Non-Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I306', 'Idli Batter', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I307', 'Sambhar Masala', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I308', 'Vermicelli', 'Veg');
INSERT INTO Ingredients (Ingredient_id, Ingredient_name, Meal_Category) VALUES ('I309', 'Flattened Rice', 'Veg');